### ISSUE TITLE
Spell Management right.

### ISSUE THREAD

**Issue by brimstone** [makerslocal/RedQueen-Project-Management#6]
In the repo name and the description.

**Comment by tylercrumpton** [comment]
Fixed with 0f66b53576c9efa497e7b0ea6b73a6cddd20f4ee.

**Comment by brimstone** [comment]
The description of the repo is still wrong.

**Comment by tylercrumpton** [comment]
Fixed with [no gitish available].

**Comment by brimstone** [comment]
Yay!
